# Generated by Django 4.2 on 2025-11-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def gen_public_ids(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    for u in User.objects.filter(public_id__isnull=True):
        u.public_id = uuid.uuid4()
        u.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Step 1: add nullable, non-unique column so schema change succeeds
        migrations.AddField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('tailor', 'Tailor')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('shirt', 'Shirt'), ('panjabi', 'Panjabi'), ('pant', 'Pant')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # Step 2: backfill unique UUIDs
        migrations.RunPython(gen_public_ids, migrations.RunPython.noop),
        # Step 3: enforce constraints and default for new rows
        migrations.AlterField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
