# Generated by Django 4.2 on 2025-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_public_id_customuser_role_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
