# Generated by Django 4.2 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_custom_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_regular_size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
