# Generated by Django 4.2 on 2025-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_tailorservice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorservice',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
