# Generated by Django 4.2 on 2025-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service_type',
            field=models.CharField(choices=[('new', 'Make New Cloth'), ('alter', 'Alter Cloth'), ('repair', 'Repair damaged cloth')], default='new', max_length=10),
        ),
    ]
