# Generated by Django 4.2 on 2025-11-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_orderitem_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='design_preference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='measurement_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('custom', 'Custom')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='regular_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailor_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
