# Generated by Django 4.2 on 2025-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_custom_measurements_order_design_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_measurements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurement_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('custom', 'Custom')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='regular_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10),
        ),
    ]
